sudo: false

language: php

php:
#  - 5.3
#  - 5.4
#  - 5.5
  - 5.6
#  - 7.0
#  - 7.1
#  - hhvm
#  - nightly

#env:
#  - DB=mysql
#  - DB=pgsql

#services:
#  - mysql
#  - postgresql

#addons:
#  postgresql: 9.6
#  mariadb: 10.1

before_script:
  - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar

script:
  - php php-cs-fixer.phar fix --verbose --dry-run
